{% set name = "colorlover" %}
{% set version = "0.3.0" %}
{% set sha256 = "b8fb7246ab46e1f5e6715649453c1762e245a515de5ff2d2b4aab7a6e67fa4e2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    
test:
  imports:
    - colorlover
    
about:
  home: https://github.com/jackparmer/colorlover
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Color scales in Python for humans'
  description: Color scales for humans  
  doc_url: https://github.com/jackparmer/colorlover
  dev_url: https://github.com/jackparmer/colorlover

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
